### ISSUE TITLE
Limit access to the broadcast

### ISSUE THREAD

**Issue by finster-** [rdubigny/cozy-music#20]
Would it be possible to set up some kind of access limitation for the broadcast? 
It feels some kind of strange that everyone, who somehow got the url, can listen to my music...

**Comment by rdubigny** [comment]
You could restrict access via IP addresses (in the app itself or in your server configuration or in your router).

Actually, I see no other simple way to do that properly. The guest need to identify somehow to the cozy. You can manage that by creating guess access to your cozy. As far as I know this service is not provided by the cozy platform at the moment.

**Comment by finster-** [comment]
>You could restrict access via IP addresses
With dynamic ip it's not that practical...so i will wait and see :)
